package ru.narod.vn91.pointsop.gui;

import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import ru.narod.vn91.pointsop.data.Player;
import ru.narod.vn91.pointsop.data.TimeSettings;
import ru.narod.vn91.pointsop.server.MockServerForGui;
import ru.narod.vn91.pointsop.server.ServerInterface;

public class GameInvitePersonal extends javax.swing.JDialog {
	ServerInterface server;
	Player player;
	SpinnerNumberModel spinnerStarting;
	SpinnerNumberModel spinnerPeriodAdditional;
	SpinnerNumberModel spinnerPeriodTransient;
	SpinnerNumberModel spinnerPeriodLength;

	/** Creates new form GameInvitePersonal2 */
	public GameInvitePersonal(java.awt.Frame parent, boolean modal, Player player) {
		super(parent, modal);

		this.server = player.server;
		this.player = player;

		TimeSettings max = server.getTimeSettingsMaximum();
		TimeSettings min = server.getTimeSettingsMinimum();
		TimeSettings def = server.getTimeSettingsDefault();
		spinnerStarting = new SpinnerNumberModel(
			def.starting / 60,
			min.starting / 60, max.starting / 60, 1);
		spinnerPeriodAdditional = new SpinnerNumberModel(
			def.periodAdditional,
			min.periodAdditional, max.periodAdditional, 1);
		spinnerPeriodTransient = new SpinnerNumberModel(
			def.periodTransient,
			min.periodTransient, max.periodTransient, 1);
		spinnerPeriodLength = new SpinnerNumberModel(
			def.periodLength,
			min.periodLength, max.periodLength, 1);
		initComponents();
		jRadioButton_Field2020.setEnabled(server.isField20x20Allowed());
		jRadioButton_Field2525.setEnabled(server.isField25x25Allowed());
		jRadioButton_Field3030.setEnabled(server.isField30x30Allowed());
		jRadioButton_Field3932.setEnabled(server.isField39x32Allowed());
		if (server.isField20x20Allowed()==true) {
			jRadioButton_Field2020.setSelected(true);
		}
		else if (server.isField25x25Allowed() == true) {
			jRadioButton_Field2525.setSelected(true);
		}
		else if (server.isField30x30Allowed() == true) {
			jRadioButton_Field3030.setSelected(true);
		}
		else if (server.isField39x32Allowed() == true) {
			jRadioButton_Field3932.setSelected(true);
		}
		jRadioButton_StartingEmpty.setEnabled(server.isStartingEmptyFieldAllowed());
		jRadioButton_StartingCross.setEnabled(server.isStartingCrossAllowed());
		jRadioButton_Starting4cross.setEnabled(server.isStarting4CrossAllowed());
		if (server.isStartingCrossAllowed()) {
			jRadioButton_StartingCross.setSelected(true);
		}
		else if (server.isStarting4CrossAllowed()) {
			jRadioButton_Starting4cross.setSelected(true);
		}
		else if (server.isStartingEmptyFieldAllowed()) {
			jRadioButton_StartingEmpty.setSelected(true);
		}
		if (max.periodAdditional <= 0) {
			int index = jTabbedPane_Time.indexOfComponent(jPanel_Zagram);
			jTabbedPane_Time.setEnabledAt(index, false);
			jTabbedPane_Time.setSelectedComponent(jPanel_Irc);
		}
		if (max.periodTransient <= 0) {
			int index = jTabbedPane_Time.indexOfComponent(jPanel_Irc);
			jTabbedPane_Time.setEnabledAt(index, false);
			jTabbedPane_Time.setSelectedComponent(jPanel_Zagram);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_FieldSize = new javax.swing.ButtonGroup();
        buttonGroup_StartingPosition = new javax.swing.ButtonGroup();
        buttonGroup_IsRating = new javax.swing.ButtonGroup();
        jPanel_FieldSize = new javax.swing.JPanel();
        jRadioButton_Field2020 = new javax.swing.JRadioButton();
        jRadioButton_Field2525 = new javax.swing.JRadioButton();
        jRadioButton_Field3030 = new javax.swing.JRadioButton();
        jRadioButton_Field3932 = new javax.swing.JRadioButton();
        jPanel_StartingPosition = new javax.swing.JPanel();
        jRadioButton_StartingEmpty = new javax.swing.JRadioButton();
        jRadioButton_StartingCross = new javax.swing.JRadioButton();
        jRadioButton_Starting4cross = new javax.swing.JRadioButton();
        jPanel_Time = new javax.swing.JPanel();
        jTabbedPane_Time = new javax.swing.JTabbedPane();
        jPanel_Zagram = new javax.swing.JPanel();
        jSpinner_TimeStarting = new JSpinner(spinnerStarting);
        jSpinner_TimePeriodAdditional = new JSpinner(spinnerPeriodAdditional);
        jPanel_Irc = new javax.swing.JPanel();
        jSpinner_TimePeriodTransient = new JSpinner(spinnerPeriodTransient);
        jSpinner_TimePeriodLength = new JSpinner(spinnerPeriodLength);
        jButton_Invite = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton_Ranked = new javax.swing.JRadioButton();
        jRadioButton_Unranked = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel_FieldSize.setBorder(javax.swing.BorderFactory.createTitledBorder("размер поля"));

        buttonGroup_FieldSize.add(jRadioButton_Field2020);
        jRadioButton_Field2020.setText("20*20");

        buttonGroup_FieldSize.add(jRadioButton_Field2525);
        jRadioButton_Field2525.setText("25*25");

        buttonGroup_FieldSize.add(jRadioButton_Field3030);
        jRadioButton_Field3030.setText("30*30");

        buttonGroup_FieldSize.add(jRadioButton_Field3932);
        jRadioButton_Field3932.setText("39*32");

        javax.swing.GroupLayout jPanel_FieldSizeLayout = new javax.swing.GroupLayout(jPanel_FieldSize);
        jPanel_FieldSize.setLayout(jPanel_FieldSizeLayout);
        jPanel_FieldSizeLayout.setHorizontalGroup(
            jPanel_FieldSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FieldSizeLayout.createSequentialGroup()
                .addComponent(jRadioButton_Field2020)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_Field2525)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_Field3030)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_Field3932)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_FieldSizeLayout.setVerticalGroup(
            jPanel_FieldSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FieldSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton_Field2020)
                .addComponent(jRadioButton_Field2525)
                .addComponent(jRadioButton_Field3030)
                .addComponent(jRadioButton_Field3932))
        );

        jPanel_StartingPosition.setBorder(javax.swing.BorderFactory.createTitledBorder("стартовая позиция"));

        buttonGroup_StartingPosition.add(jRadioButton_StartingEmpty);
        jRadioButton_StartingEmpty.setText("пустое поле");

        buttonGroup_StartingPosition.add(jRadioButton_StartingCross);
        jRadioButton_StartingCross.setText("скрест");

        buttonGroup_StartingPosition.add(jRadioButton_Starting4cross);
        jRadioButton_Starting4cross.setText("4 скреста");

        javax.swing.GroupLayout jPanel_StartingPositionLayout = new javax.swing.GroupLayout(jPanel_StartingPosition);
        jPanel_StartingPosition.setLayout(jPanel_StartingPositionLayout);
        jPanel_StartingPositionLayout.setHorizontalGroup(
            jPanel_StartingPositionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_StartingPositionLayout.createSequentialGroup()
                .addComponent(jRadioButton_StartingEmpty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_StartingCross)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_Starting4cross)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel_StartingPositionLayout.setVerticalGroup(
            jPanel_StartingPositionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_StartingPositionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton_StartingEmpty)
                .addComponent(jRadioButton_StartingCross)
                .addComponent(jRadioButton_Starting4cross))
        );

        jPanel_Time.setBorder(javax.swing.BorderFactory.createTitledBorder("настройки времени"));

        jSpinner_TimeStarting.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "начальное время, мин"));

        jSpinner_TimePeriodAdditional.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "добавочное время за ход, сек"));

        javax.swing.GroupLayout jPanel_ZagramLayout = new javax.swing.GroupLayout(jPanel_Zagram);
        jPanel_Zagram.setLayout(jPanel_ZagramLayout);
        jPanel_ZagramLayout.setHorizontalGroup(
            jPanel_ZagramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSpinner_TimeStarting, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
            .addComponent(jSpinner_TimePeriodAdditional, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );
        jPanel_ZagramLayout.setVerticalGroup(
            jPanel_ZagramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ZagramLayout.createSequentialGroup()
                .addComponent(jSpinner_TimeStarting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner_TimePeriodAdditional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane_Time.addTab("с накоплением", jPanel_Zagram);

        jSpinner_TimePeriodTransient.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "даётся # секунд"));

        jSpinner_TimePeriodLength.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "на каждые # ходов"));

        javax.swing.GroupLayout jPanel_IrcLayout = new javax.swing.GroupLayout(jPanel_Irc);
        jPanel_Irc.setLayout(jPanel_IrcLayout);
        jPanel_IrcLayout.setHorizontalGroup(
            jPanel_IrcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSpinner_TimePeriodLength, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
            .addComponent(jSpinner_TimePeriodTransient, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );
        jPanel_IrcLayout.setVerticalGroup(
            jPanel_IrcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_IrcLayout.createSequentialGroup()
                .addComponent(jSpinner_TimePeriodLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner_TimePeriodTransient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane_Time.addTab("со сгоранием", jPanel_Irc);

        javax.swing.GroupLayout jPanel_TimeLayout = new javax.swing.GroupLayout(jPanel_Time);
        jPanel_Time.setLayout(jPanel_TimeLayout);
        jPanel_TimeLayout.setHorizontalGroup(
            jPanel_TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Time, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );
        jPanel_TimeLayout.setVerticalGroup(
            jPanel_TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton_Invite.setText("Вызвать на игру");
        jButton_Invite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InviteActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("тип игры"));

        buttonGroup_IsRating.add(jRadioButton_Ranked);
        jRadioButton_Ranked.setText("рейтинговая");

        buttonGroup_IsRating.add(jRadioButton_Unranked);
        jRadioButton_Unranked.setSelected(true);
        jRadioButton_Unranked.setText("нерейтинговая");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jRadioButton_Ranked)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_Unranked)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton_Ranked)
                .addComponent(jRadioButton_Unranked))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_FieldSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_StartingPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_Invite, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_FieldSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_StartingPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Invite))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jButton_InviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InviteActionPerformed
		int fieldX, fieldY;
		if (jRadioButton_Field2020.isSelected()) {
			fieldX = 20;
			fieldY = 20;
		}
		else if (jRadioButton_Field2525.isSelected()) {
			fieldX = 25;
			fieldY = 25;
		}
		else if (jRadioButton_Field3030.isSelected()) {
			fieldX = 30;
			fieldY = 30;
		}
		else if (jRadioButton_Field3932.isSelected()) {
			fieldX = 39;
			fieldY = 32;
		} else {
			fieldX = 20;
			fieldY = 20;
		}
		TimeSettings timeSettings = new TimeSettings(
						spinnerStarting.getNumber().intValue() * 60, 
						spinnerPeriodAdditional.getNumber().intValue(),
						spinnerPeriodTransient.getNumber().intValue(),
						spinnerPeriodLength.getNumber().intValue(),
						0);
		server.addPersonalGameInvite(player.id, timeSettings, fieldX, fieldY, jRadioButton_Ranked.isSelected());
		this.dispose();
	}//GEN-LAST:event_jButton_InviteActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				GameInvitePersonal dialog = new GameInvitePersonal(new javax.swing.JFrame(), true, 
								new Player(new MockServerForGui(), "userId"));
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {

					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_FieldSize;
    private javax.swing.ButtonGroup buttonGroup_IsRating;
    private javax.swing.ButtonGroup buttonGroup_StartingPosition;
    private javax.swing.JButton jButton_Invite;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_FieldSize;
    private javax.swing.JPanel jPanel_Irc;
    private javax.swing.JPanel jPanel_StartingPosition;
    private javax.swing.JPanel jPanel_Time;
    private javax.swing.JPanel jPanel_Zagram;
    private javax.swing.JRadioButton jRadioButton_Field2020;
    private javax.swing.JRadioButton jRadioButton_Field2525;
    private javax.swing.JRadioButton jRadioButton_Field3030;
    private javax.swing.JRadioButton jRadioButton_Field3932;
    private javax.swing.JRadioButton jRadioButton_Ranked;
    private javax.swing.JRadioButton jRadioButton_Starting4cross;
    private javax.swing.JRadioButton jRadioButton_StartingCross;
    private javax.swing.JRadioButton jRadioButton_StartingEmpty;
    private javax.swing.JRadioButton jRadioButton_Unranked;
    private javax.swing.JSpinner jSpinner_TimePeriodAdditional;
    private javax.swing.JSpinner jSpinner_TimePeriodLength;
    private javax.swing.JSpinner jSpinner_TimePeriodTransient;
    private javax.swing.JSpinner jSpinner_TimeStarting;
    private javax.swing.JTabbedPane jTabbedPane_Time;
    // End of variables declaration//GEN-END:variables
}
