package ru.narod.vn91.pointsop.gui;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ru.narod.vn91.pointsop.server.ServerInterface;

public class LangRoom extends javax.swing.JPanel implements RoomInterface {

	ServerInterface server;
	String nameOnServer;
	GuiController centralGuiController;

	public JPanel getMainJPanel() {
		return this;
	}

	public RoomPart_Chat getRoomPart_Chat() {
		return roomPart_Chat1;
	}

	public RoomPart_Userlist getRoomPart_UserList() {
		return roomPart_UserList1;
	}

	public RoomPart_GameList getRoomPart_GameList() {
		return roomPart_GameList1;
	}

	public Paper getRoomPart_Paper() {
		return null;
	}

	public PrivateChat getPrivateChat() {
		return null;
	}

	public ServerInterface getServer() {
		return server;
	}

	public String getRoomNameOnServer() {
		return nameOnServer;
	}

	public boolean close() {
		getServer().unsubscribeRoom(nameOnServer);
		return false;
	}

	/** Creates new form ContainerRoom_Lang */
	public LangRoom(
			ServerInterface server,
			String nameOnServer,
			GuiController centralGuiController) {
		this.server = server;
		this.nameOnServer = nameOnServer;
		this.centralGuiController = centralGuiController;
		initComponents();

		roomPart_Chat1.initRoomPart(this);
		roomPart_UserList1.initRoomPart(this, centralGuiController);
		roomPart_GameList1.initRoomPart(this, centralGuiController);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomPart_Chat1 = new ru.narod.vn91.pointsop.gui.RoomPart_Chat();
        roomPart_GameList1 = new ru.narod.vn91.pointsop.gui.RoomPart_GameList();
        roomPart_UserList1 = new ru.narod.vn91.pointsop.gui.RoomPart_Userlist();
        jButton_SearchOpponent = new javax.swing.JButton();
        jButton_StopSearchingOpponent = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jButton_SearchOpponent.setText("оставить заявку на игру");
        jButton_SearchOpponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchOpponentActionPerformed(evt);
            }
        });

        jButton_StopSearchingOpponent.setText("отменить заявку");
        jButton_StopSearchingOpponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StopSearchingOpponentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomPart_GameList1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addComponent(roomPart_Chat1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(roomPart_UserList1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(jButton_SearchOpponent, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(jButton_StopSearchingOpponent, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(roomPart_GameList1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roomPart_Chat1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(roomPart_UserList1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton_SearchOpponent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_StopSearchingOpponent))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void jButton_SearchOpponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchOpponentActionPerformed
		server.searchOpponent();
		JOptionPane.showMessageDialog(this,
				"В связи дурацкой особенностью сервера, "
				+ "эта кнопка не работает если жать её слишком часто.\n "
				+ "Постарайтесь жать только когда необходимо..");
	}//GEN-LAST:event_jButton_SearchOpponentActionPerformed

	private void jButton_StopSearchingOpponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StopSearchingOpponentActionPerformed
		server.stopSearchingOpponent();
		JOptionPane.showMessageDialog(this,
				"В связи дурацкой особенностью сервера, "
				+ "эта кнопка не работает если жать её слишком часто.\n "
				+ "Постарайтесь жать только когда необходимо..");
	}//GEN-LAST:event_jButton_StopSearchingOpponentActionPerformed

	private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
		roomPart_Chat1.requestFocusInWindow();
	}//GEN-LAST:event_formFocusGained

	private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
		roomPart_Chat1.requestFocusInWindow();
	}//GEN-LAST:event_formComponentShown
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_SearchOpponent;
    private javax.swing.JButton jButton_StopSearchingOpponent;
    private ru.narod.vn91.pointsop.gui.RoomPart_Chat roomPart_Chat1;
    private ru.narod.vn91.pointsop.gui.RoomPart_GameList roomPart_GameList1;
    private ru.narod.vn91.pointsop.gui.RoomPart_Userlist roomPart_UserList1;
    // End of variables declaration//GEN-END:variables
}
