package ru.narod.vn91.pointsop.gui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import ru.narod.vn91.pointsop.model.GuiController;
import ru.narod.vn91.pointsop.model.GuiForServerInterface;
import ru.narod.vn91.pointsop.server.ServerInterface;

public class LangRoom extends javax.swing.JPanel implements RoomInterface {

	ServerInterface server;
	String nameOnServer;
	GuiForServerInterface centralGuiController;

	@Override
	public JPanel getMainJPanel() {
		return this;
	}

	@Override
	public RoomPart_Chat getRoomPart_Chat() {
		return roomPart_Chat;
	}

	@Override
	public RoomPart_Userlist getRoomPart_UserList() {
		return roomPart_UserList;
	}

	@Override
	public RoomPart_GameList getRoomPart_GameList() {
		return roomPart_GameList1;
	}

	@Override
	public Paper getRoomPart_Paper() {
		return null;
	}

	@Override
	public PrivateChat getPrivateChat() {
		return null;
	}

	@Override
	public ServerInterface getServer() {
		return server;
	}

	@Override
	public String getRoomNameOnServer() {
		return nameOnServer;
	}

	@Override
	public boolean userAsksClose() {
		getServer().unsubscribeRoom(nameOnServer);
		return false;
	}

	public void statusSet(boolean isBusy) {
		jComboBox1.setSelectedIndex(isBusy ? 1 : 0);
	}
	
	/** Creates new form ContainerRoom_Lang */
	public LangRoom(
			ServerInterface server,
			String nameOnServer,
			GuiController centralGuiController) {
		this.nameOnServer = nameOnServer;
		this.centralGuiController = centralGuiController;
		initComponents();
		jToggleButton_LeaveZayavkaActionPerformed(null);
		this.server = server;

		roomPart_Chat.initChat(this, null);
		roomPart_UserList.initRoomPart(this, centralGuiController);
		roomPart_GameList1.initRoomPart(this, centralGuiController);
		jToggleButton_LeaveZayavka.setVisible(server.isGlobalGameVacancyAllowed());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jSplitPane_Global = new javax.swing.JSplitPane();
        jPanel_GameListAndChat = new javax.swing.JPanel();
        jSplitPane_GameListAndChat = new javax.swing.JSplitPane();
        jPanel_GameList = new javax.swing.JPanel();
        roomPart_GameList1 = new ru.narod.vn91.pointsop.gui.RoomPart_GameList();
        jPanel_Toolbar = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jToggleButton_LeaveZayavka = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        roomPart_Chat = new ru.narod.vn91.pointsop.gui.RoomPart_Chat();
        roomPart_UserList = new ru.narod.vn91.pointsop.gui.RoomPart_Userlist();

        jButton1.setText("!топ");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jSplitPane_Global.setResizeWeight(1.0);
        jSplitPane_Global.setContinuousLayout(true);

        jSplitPane_GameListAndChat.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane_GameListAndChat.setResizeWeight(0.33);
        jSplitPane_GameListAndChat.setContinuousLayout(true);

        jPanel_Toolbar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "свободен", "занят" }));
        jComboBox1.setToolTipText("<html>В случае статуса \"занят\" <br>приглашения на игру автоматически отклоняются.</html>");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jToggleButton_LeaveZayavka.setText("заявка на игру");
        jToggleButton_LeaveZayavka.setFocusable(false);
        jToggleButton_LeaveZayavka.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton_LeaveZayavkaStateChanged(evt);
            }
        });
        jToggleButton_LeaveZayavka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_LeaveZayavkaActionPerformed(evt);
            }
        });

        jButton2.setText(".?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ToolbarLayout = new javax.swing.GroupLayout(jPanel_Toolbar);
        jPanel_Toolbar.setLayout(jPanel_ToolbarLayout);
        jPanel_ToolbarLayout.setHorizontalGroup(
            jPanel_ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ToolbarLayout.createSequentialGroup()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton_LeaveZayavka))
        );
        jPanel_ToolbarLayout.setVerticalGroup(
            jPanel_ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToggleButton_LeaveZayavka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel_GameListLayout = new javax.swing.GroupLayout(jPanel_GameList);
        jPanel_GameList.setLayout(jPanel_GameListLayout);
        jPanel_GameListLayout.setHorizontalGroup(
            jPanel_GameListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(roomPart_GameList1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );
        jPanel_GameListLayout.setVerticalGroup(
            jPanel_GameListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_GameListLayout.createSequentialGroup()
                .addComponent(roomPart_GameList1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane_GameListAndChat.setLeftComponent(jPanel_GameList);

        roomPart_Chat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        roomPart_Chat.setMinimumSize(null);
        roomPart_Chat.setPreferredSize(null);
        jSplitPane_GameListAndChat.setRightComponent(roomPart_Chat);

        javax.swing.GroupLayout jPanel_GameListAndChatLayout = new javax.swing.GroupLayout(jPanel_GameListAndChat);
        jPanel_GameListAndChat.setLayout(jPanel_GameListAndChatLayout);
        jPanel_GameListAndChatLayout.setHorizontalGroup(
            jPanel_GameListAndChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane_GameListAndChat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );
        jPanel_GameListAndChatLayout.setVerticalGroup(
            jPanel_GameListAndChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane_GameListAndChat, javax.swing.GroupLayout.PREFERRED_SIZE, 145, Short.MAX_VALUE)
        );

        jSplitPane_Global.setLeftComponent(jPanel_GameListAndChat);
        jSplitPane_Global.setRightComponent(roomPart_UserList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSplitPane_Global)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane_Global, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

	private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
		roomPart_Chat.requestFocusInWindow();
	}//GEN-LAST:event_formFocusGained

	private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
		roomPart_Chat.requestFocusInWindow();
	}//GEN-LAST:event_formComponentShown

private void jToggleButton_LeaveZayavkaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton_LeaveZayavkaStateChanged

}//GEN-LAST:event_jToggleButton_LeaveZayavkaStateChanged

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
	JOptionPane.showMessageDialog(null, 
					"Ваши предложения, что сюда добавить?\n"
					+ "\n"
					+ "Для PointsXT - может быть команды?\n"
					+ "Для zagram - может быть фильтрация заявок на игру (автоприём, автоотказ) ?\n"
					+ "\n"
					+ "http://pointsgame.net/forum/");
}//GEN-LAST:event_jButton2ActionPerformed

private void jToggleButton_LeaveZayavkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_LeaveZayavkaActionPerformed
	if (jToggleButton_LeaveZayavka.isSelected()) {
		jToggleButton_LeaveZayavka.setText("убрать заявку на игру");
		jToggleButton_LeaveZayavka.setIcon(new ImageIcon());
		if (evt != null && server != null) {
			server.createGameVacancy();
		}
	} else {
		jToggleButton_LeaveZayavka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ru/narod/vn91/pointsop/gui/new.png")));
		jToggleButton_LeaveZayavka.setText("оставить заявку на игру");
		if (server != null) {
			server.stopGameVacancy();
		}
	}
}//GEN-LAST:event_jToggleButton_LeaveZayavkaActionPerformed

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
		server.setStatus(jComboBox1.getSelectedIndex() == 1);
	}//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel_GameList;
    private javax.swing.JPanel jPanel_GameListAndChat;
    private javax.swing.JPanel jPanel_Toolbar;
    private javax.swing.JSplitPane jSplitPane_GameListAndChat;
    private javax.swing.JSplitPane jSplitPane_Global;
    private javax.swing.JToggleButton jToggleButton_LeaveZayavka;
    private ru.narod.vn91.pointsop.gui.RoomPart_Chat roomPart_Chat;
    private ru.narod.vn91.pointsop.gui.RoomPart_GameList roomPart_GameList1;
    private ru.narod.vn91.pointsop.gui.RoomPart_Userlist roomPart_UserList;
    // End of variables declaration//GEN-END:variables
}
