package ru.narod.vn91.pointsop.gui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JColorChooser;
import ru.narod.vn91.pointsop.sounds.Sounds;
import ru.narod.vn91.pointsop.utils.CustomColors;
import ru.narod.vn91.pointsop.utils.Settings;
import ru.narod.vn91.pointsop.utils.Settings.ClickAudibility;

@SuppressWarnings("serial")
public class SettingsPanel extends javax.swing.JPanel {

	private boolean initPhase = true;
	private Paper paper = new Paper() {
		@Override
		public void paperClick(int x, int y, MouseEvent evt) {
		}

		@Override
		public void paperMouseMove(int x, int y, MouseEvent evt) {
		}
	};

	class PointsClickListener implements ActionListener {

		public void actionPerformed(ActionEvent e) {
			Settings.setClickAudibility(e.getActionCommand());
		}
	}
	PointsClickListener pointsClickListener = new PointsClickListener();

	class PrivateChatListener implements ActionListener {

		public void actionPerformed(ActionEvent e) {
//			Memory.memory.put("PrivateChat", e.getActionCommand());
		}
	}
	PrivateChatListener privateChatListener = new PrivateChatListener();

	private void setColors() {
		Color p1 = Settings.getPlayer1Color();
		Color p2 = Settings.getPlayer2Color();
		Color back = Settings.getBackgroundColor();
		jButton_P1Color.setBackground(p1);
		jButton_P2Color.setBackground(p2);
		jButton_BackgroundColor.setBackground(back);
		jButton_P1Color.setForeground(CustomColors.getContrastColor(p1));
		jButton_P2Color.setForeground(CustomColors.getContrastColor(p2));
		jButton_BackgroundColor.setForeground(CustomColors.getContrastColor(back));
		paper.repaint();
	}

	/** Creates new form SettingsPanel */
	public SettingsPanel() {
		paper.initPaper(4, 3, false);
		paper.makeMove(true, 2, 1, true);
		paper.makeMove(true, 1, 2, true);
		paper.makeMove(true, 3, 2, true);
		paper.makeMove(true, 2, 3, true);
		paper.makeMove(true, 2, 2, false);
		paper.makeMove(true, 3, 1, false);
		paper.makeMove(true, 4, 1, false);
		paper.makeMove(true, 3, 3, false);
		paper.makeMove(false, 4, 2, false);
		initComponents();
		jRadioButton_PointsClick_InAllGames.setActionCommand(
				ClickAudibility.IN_ALL_GAMES.name());
		jRadioButton_PointsClick_OnlyInMyGames.setActionCommand(
				ClickAudibility.IN_MY_GAMES.name());
		jRadioButton_PointsClick_Nowhere.setActionCommand(
				ClickAudibility.NOWHERE.name());
//		jSlider1.setValueIsAdjusting(true);
		jSlider_DotWidth.setValue(
				(int)(Settings.getDotWidth()
				* (jSlider_DotWidth.getMaximum() - jSlider_DotWidth.getMinimum() + 1)
				+ 0.5));
//		jSlider1.setValueIsAdjusting(false);
		jCheckBox_DrawConnections.setSelected(
				Settings.getDrawConnections());
		setColors();
		jCheckBox_OtherSounds.setSelected(Settings.getOtherSounds());
		{
			Enumeration<AbstractButton> pointClickButtons = buttonGroup_PointClick.getElements();
			String userSetting = Settings.getClickAudibility().name();
			for (Enumeration<AbstractButton> enumerator = pointClickButtons; enumerator.hasMoreElements();) {
				AbstractButton abstractButton = enumerator.nextElement();
				if (abstractButton.getActionCommand().equals(userSetting)) {
					abstractButton.setSelected(true);
				}
				abstractButton.addActionListener(pointsClickListener);
			}
		}
		jCheckBox_RestoreSize.setSelected(Settings.isRestoreSize());
		jCheckBox_RestorePosition.setSelected(Settings.isRestorePosition());
		jCheckBox_Animation.setSelected(Settings.getLastDotAnimation());
		initPhase = false;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_PointClick = new javax.swing.ButtonGroup();
        buttonGroup_PrivateChat = new javax.swing.ButtonGroup();
        jPanel_Click = new javax.swing.JPanel();
        jRadioButton_PointsClick_InAllGames = new javax.swing.JRadioButton();
        jRadioButton_PointsClick_OnlyInMyGames = new javax.swing.JRadioButton();
        jRadioButton_PointsClick_Nowhere = new javax.swing.JRadioButton();
        jButton_PointClick = new javax.swing.JButton();
        jPanel_PaperSettings = new javax.swing.JPanel();
        jSplitPane = new javax.swing.JSplitPane();
        jPanel_PaperSettings2 = new javax.swing.JPanel();
        jCheckBox_DrawConnections = new javax.swing.JCheckBox();
        jSlider_DotWidth = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jButton_P1Color = new javax.swing.JButton();
        jButton_P2Color = new javax.swing.JButton();
        jButton_BackgroundColor = new javax.swing.JButton();
        jButton_ResetColors = new javax.swing.JButton();
        jCheckBox_Animation = new javax.swing.JCheckBox();
        jPanel_Paper = paper;
        jPanel_OtherSounds = new javax.swing.JPanel();
        jCheckBox_OtherSounds = new javax.swing.JCheckBox();
        jPanel_AtStartup = new javax.swing.JPanel();
        jCheckBox_RestorePosition = new javax.swing.JCheckBox();
        jCheckBox_RestoreSize = new javax.swing.JCheckBox();

        jPanel_Click.setBorder(javax.swing.BorderFactory.createTitledBorder("звук постановки точек"));

        buttonGroup_PointClick.add(jRadioButton_PointsClick_InAllGames);
        jRadioButton_PointsClick_InAllGames.setSelected(true);
        jRadioButton_PointsClick_InAllGames.setText("во всех играх");
        jRadioButton_PointsClick_InAllGames.setActionCommand("InAllGames");
        jRadioButton_PointsClick_InAllGames.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton_PointsClick_InAllGamesStateChanged(evt);
            }
        });

        buttonGroup_PointClick.add(jRadioButton_PointsClick_OnlyInMyGames);
        jRadioButton_PointsClick_OnlyInMyGames.setText("только в моих играх");
        jRadioButton_PointsClick_OnlyInMyGames.setActionCommand("OnlyInMyOwnGames");

        buttonGroup_PointClick.add(jRadioButton_PointsClick_Nowhere);
        jRadioButton_PointsClick_Nowhere.setText("нигде");
        jRadioButton_PointsClick_Nowhere.setActionCommand("Nowhere");

        jButton_PointClick.setText("тест звука");
        jButton_PointClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PointClickActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ClickLayout = new javax.swing.GroupLayout(jPanel_Click);
        jPanel_Click.setLayout(jPanel_ClickLayout);
        jPanel_ClickLayout.setHorizontalGroup(
            jPanel_ClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ClickLayout.createSequentialGroup()
                .addComponent(jRadioButton_PointsClick_InAllGames)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_PointsClick_OnlyInMyGames)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_PointsClick_Nowhere)
                .addGap(18, 18, 18)
                .addComponent(jButton_PointClick)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel_ClickLayout.setVerticalGroup(
            jPanel_ClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton_PointsClick_InAllGames)
                .addComponent(jRadioButton_PointsClick_OnlyInMyGames)
                .addComponent(jRadioButton_PointsClick_Nowhere)
                .addComponent(jButton_PointClick))
        );

        jPanel_PaperSettings.setBorder(javax.swing.BorderFactory.createTitledBorder("настройки игрового поля"));
        // jPanel_PaperSettings.setVisible(false);

        jSplitPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSplitPane.setResizeWeight(1.0);
        jSplitPane.setContinuousLayout(true);

        jCheckBox_DrawConnections.setText("<html>соединять соседние точки палочками</html>");
        jCheckBox_DrawConnections.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox_DrawConnectionsStateChanged(evt);
            }
        });

        jSlider_DotWidth.setMajorTickSpacing(3);
        jSlider_DotWidth.setMaximum(17);
        jSlider_DotWidth.setMinimum(1);
        jSlider_DotWidth.setMinorTickSpacing(1);
        jSlider_DotWidth.setPaintTicks(true);
        jSlider_DotWidth.setSnapToTicks(true);
        jSlider_DotWidth.setValue(4);
        jSlider_DotWidth.setBorder(javax.swing.BorderFactory.createTitledBorder("размер точек"));
        jSlider_DotWidth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_DotWidthStateChanged(evt);
            }
        });

        jButton_P1Color.setText("игрок 1");
        jButton_P1Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_P1ColorActionPerformed(evt);
            }
        });

        jButton_P2Color.setText("игрок 2");
        jButton_P2Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_P2ColorActionPerformed(evt);
            }
        });

        jButton_BackgroundColor.setText("фон");
        jButton_BackgroundColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackgroundColorActionPerformed(evt);
            }
        });

        jButton_ResetColors.setText("восстановить цвета");
        jButton_ResetColors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetColorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton_P1Color)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_P2Color)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_BackgroundColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ResetColors)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton_P1Color)
                .addComponent(jButton_P2Color)
                .addComponent(jButton_BackgroundColor)
                .addComponent(jButton_ResetColors))
        );

        jCheckBox_Animation.setText("анимация последней поставленной точки");
        jCheckBox_Animation.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox_AnimationStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel_PaperSettings2Layout = new javax.swing.GroupLayout(jPanel_PaperSettings2);
        jPanel_PaperSettings2.setLayout(jPanel_PaperSettings2Layout);
        jPanel_PaperSettings2Layout.setHorizontalGroup(
            jPanel_PaperSettings2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PaperSettings2Layout.createSequentialGroup()
                .addComponent(jSlider_DotWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_PaperSettings2Layout.createSequentialGroup()
                .addComponent(jCheckBox_DrawConnections, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel_PaperSettings2Layout.createSequentialGroup()
                .addComponent(jCheckBox_Animation)
                .addContainerGap())
        );
        jPanel_PaperSettings2Layout.setVerticalGroup(
            jPanel_PaperSettings2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PaperSettings2Layout.createSequentialGroup()
                .addComponent(jSlider_DotWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_DrawConnections, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_Animation))
        );

        jSplitPane.setLeftComponent(jPanel_PaperSettings2);

        javax.swing.GroupLayout jPanel_PaperLayout = new javax.swing.GroupLayout(jPanel_Paper);
        jPanel_Paper.setLayout(jPanel_PaperLayout);
        jPanel_PaperLayout.setHorizontalGroup(
            jPanel_PaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );
        jPanel_PaperLayout.setVerticalGroup(
            jPanel_PaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(jPanel_Paper);

        javax.swing.GroupLayout jPanel_PaperSettingsLayout = new javax.swing.GroupLayout(jPanel_PaperSettings);
        jPanel_PaperSettings.setLayout(jPanel_PaperSettingsLayout);
        jPanel_PaperSettingsLayout.setHorizontalGroup(
            jPanel_PaperSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );
        jPanel_PaperSettingsLayout.setVerticalGroup(
            jPanel_PaperSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );

        jPanel_OtherSounds.setBorder(javax.swing.BorderFactory.createTitledBorder("прочие звуки"));

        jCheckBox_OtherSounds.setText("включены?");
        jCheckBox_OtherSounds.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox_OtherSoundsStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel_OtherSoundsLayout = new javax.swing.GroupLayout(jPanel_OtherSounds);
        jPanel_OtherSounds.setLayout(jPanel_OtherSoundsLayout);
        jPanel_OtherSoundsLayout.setHorizontalGroup(
            jPanel_OtherSoundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_OtherSoundsLayout.createSequentialGroup()
                .addComponent(jCheckBox_OtherSounds)
                .addContainerGap(449, Short.MAX_VALUE))
        );
        jPanel_OtherSoundsLayout.setVerticalGroup(
            jPanel_OtherSoundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCheckBox_OtherSounds)
        );

        jPanel_AtStartup.setBorder(javax.swing.BorderFactory.createTitledBorder("при запуске"));

        jCheckBox_RestorePosition.setText("восстанавливать позицию на экране");
        jCheckBox_RestorePosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_RestorePositionActionPerformed(evt);
            }
        });

        jCheckBox_RestoreSize.setText("восстанавливать размеры");
        jCheckBox_RestoreSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_RestoreSizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_AtStartupLayout = new javax.swing.GroupLayout(jPanel_AtStartup);
        jPanel_AtStartup.setLayout(jPanel_AtStartupLayout);
        jPanel_AtStartupLayout.setHorizontalGroup(
            jPanel_AtStartupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AtStartupLayout.createSequentialGroup()
                .addGroup(jPanel_AtStartupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_RestorePosition)
                    .addComponent(jCheckBox_RestoreSize))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel_AtStartupLayout.setVerticalGroup(
            jPanel_AtStartupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AtStartupLayout.createSequentialGroup()
                .addComponent(jCheckBox_RestorePosition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_RestoreSize))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Click, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_OtherSounds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_PaperSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_AtStartup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Click, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_OtherSounds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_PaperSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_AtStartup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void jRadioButton_PointsClick_InAllGamesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton_PointsClick_InAllGamesStateChanged
	}//GEN-LAST:event_jRadioButton_PointsClick_InAllGamesStateChanged

	private void jButton_PointClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PointClickActionPerformed
		Sounds.playMakeMove(true);
	}//GEN-LAST:event_jButton_PointClickActionPerformed

	private void jSlider_DotWidthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_DotWidthStateChanged
		if (initPhase == false) {
			Settings.setDotWidth(
					((double) jSlider_DotWidth.getValue())
							/ jSlider_DotWidth.getMaximum()
			);
			paper.repaint();
		}
	}//GEN-LAST:event_jSlider_DotWidthStateChanged

	private void jCheckBox_DrawConnectionsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox_DrawConnectionsStateChanged
		Settings.setDrawConnections(
				jCheckBox_DrawConnections.isSelected()
		);
		paper.repaint();
	}//GEN-LAST:event_jCheckBox_DrawConnectionsStateChanged

	private void jButton_P1ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_P1ColorActionPerformed
		Color c = JColorChooser.showDialog(null, "цвет первого игрока",
				Settings.getPlayer1Color());
		if (c != null) {
			Settings.setPlayer1Color(c, true);
			setColors();
		}
	}//GEN-LAST:event_jButton_P1ColorActionPerformed

	private void jButton_P2ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_P2ColorActionPerformed
		Color c = JColorChooser.showDialog(null, "цвет второго игрока",
				Settings.getPlayer2Color());
		if (c != null) {
			Settings.setPlayer2Color(c, true);
			setColors();
		}
	}//GEN-LAST:event_jButton_P2ColorActionPerformed

	private void jButton_BackgroundColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackgroundColorActionPerformed
		Color c = JColorChooser.showDialog(null, "цвет первого игрока",
				Settings.getBackgroundColor());
		if (c != null) {
			Settings.setBackgroundColor(c, true);
			setColors();
		}

	}//GEN-LAST:event_jButton_BackgroundColorActionPerformed

	private void jButton_ResetColorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetColorsActionPerformed
		Settings.resetColors();
		setColors();
	}//GEN-LAST:event_jButton_ResetColorsActionPerformed

private void jCheckBox_OtherSoundsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox_OtherSoundsStateChanged
	Settings.setOtherSounds(jCheckBox_OtherSounds.isSelected());
}//GEN-LAST:event_jCheckBox_OtherSoundsStateChanged

	private void jCheckBox_RestorePositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_RestorePositionActionPerformed
		Settings.setRestorePosition(jCheckBox_RestorePosition.isSelected());
	}//GEN-LAST:event_jCheckBox_RestorePositionActionPerformed

	private void jCheckBox_RestoreSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_RestoreSizeActionPerformed
		Settings.setRestoreSize(jCheckBox_RestoreSize.isSelected());
	}//GEN-LAST:event_jCheckBox_RestoreSizeActionPerformed

	private void jCheckBox_AnimationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox_AnimationStateChanged
		Settings.setLastDotAnimation(jCheckBox_Animation.isSelected());
	}//GEN-LAST:event_jCheckBox_AnimationStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_PointClick;
    private javax.swing.ButtonGroup buttonGroup_PrivateChat;
    private javax.swing.JButton jButton_BackgroundColor;
    private javax.swing.JButton jButton_P1Color;
    private javax.swing.JButton jButton_P2Color;
    private javax.swing.JButton jButton_PointClick;
    private javax.swing.JButton jButton_ResetColors;
    private javax.swing.JCheckBox jCheckBox_Animation;
    private javax.swing.JCheckBox jCheckBox_DrawConnections;
    private javax.swing.JCheckBox jCheckBox_OtherSounds;
    private javax.swing.JCheckBox jCheckBox_RestorePosition;
    private javax.swing.JCheckBox jCheckBox_RestoreSize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_AtStartup;
    private javax.swing.JPanel jPanel_Click;
    private javax.swing.JPanel jPanel_OtherSounds;
    private javax.swing.JPanel jPanel_Paper;
    private javax.swing.JPanel jPanel_PaperSettings;
    private javax.swing.JPanel jPanel_PaperSettings2;
    private javax.swing.JRadioButton jRadioButton_PointsClick_InAllGames;
    private javax.swing.JRadioButton jRadioButton_PointsClick_Nowhere;
    private javax.swing.JRadioButton jRadioButton_PointsClick_OnlyInMyGames;
    private javax.swing.JSlider jSlider_DotWidth;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
